import { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { useSettings } from './SettingsContext';
import { useAuth } from './AuthContext';

type Language = 'id' | 'en' | 'de' | 'zh' | 'ja' | 'es' | 'pt' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  availableLanguages: { code: Language; label: string; flag: string }[];
  // For public pages - use owner's language preference
  ownerLanguage: Language | null;
  setOwnerLanguage: (lang: Language) => void;
  // For determining which language to use (public vs authenticated)
  effectiveLanguage: Language;
  isPublicContext: boolean;
  setIsPublicContext: (isPublic: boolean) => void;
}

const translations: Record<Language, Record<string, string>> = {
  id: {
    // URL Found Page
    loading: 'Memuat...',
    urlNotFound: 'URL Tidak Ditemukan',
    urlNotFoundMessage: 'Tautan yang Anda cari tidak ditemukan atau telah dihapus.',
    goToHomepage: 'Kembali ke Beranda',
    passwordProtected: 'URL Dilindungi Password',
    accessBlocked: 'Akses Diblokir',
    enterPassword: 'Masukkan Password',
    passwordPlaceholder: 'Masukkan password',
    unlock: 'Buka Kunci',
    verifying: 'Memverifikasi...',
    attempts: 'Percobaan',
    caseSensitive: 'Password case-sensitive',
    wrongPassword: 'Password salah',
    remainingAttempts: 'Sisa percobaan',
    maxAttemptsReached: 'Anda telah melebihi percobaan maksimal',
    tips: 'Tips',
    caseSensitiveTip: 'Password bersifat case-sensitive (huruf besar/kecil berbeda). Pastikan Caps Lock tidak aktif.',
    contactOwner: 'Hubungi pemilik tautan untuk mendapatkan password yang benar.',
    publicAccess: 'Akses publik',
    protectedInfo: 'informasi ini dilindungi',
    urlFound: 'URL Ditemukan!',
    redirecting: 'Redirect dalam...',
    shortUrl: 'Short URL',
    linkInfo: 'Informasi Link',
    targetUrl: 'Target URL',
    preparing: 'Mempersiapkan redirect...',
    autoRedirectDisabled: 'Auto-redirect dinonaktifkan. Klik tombol untuk redirect.',
    redirectNow: 'Redirect Sekarang',
    redirectingTo: 'Anda akan diarahkan ke',
    redirectInSeconds: 'Mengalihkan ke halaman tujuan dalam {seconds} detik...',
    passwordFailed: 'Percobaan gagal',
    
    // Public HTML Pages
    welcomeTitle: 'Selamat Datang di modernURL8',
    welcomeMessage: 'Ini adalah layanan pengalihan URL. Silakan gunakan URL pendek yang valid untuk dialihkan.',
    goToHome: 'Ke Beranda',
    notFoundTitle: 'Tautan Tidak Ditemukan',
    notFoundMessage: 'URL pendek yang Anda masukkan tidak ada atau telah dihapus. Silakan periksa URL dan coba lagi.',
    expiredTitle: 'Tautan Kadaluarsa',
    expiredMessage: 'URL pendek ini telah kedaluwarsa dan tidak lagi tersedia.',
    
    // Kelola Pages
    dashboard: 'Dashboard',
    urls: 'URLs',
    users: 'Users',
    settings: 'Pengaturan',
    logout: 'Keluar',
    manageUrls: 'Kelola URL',
    createUrl: 'Buat URL',
    editUrl: 'Edit URL',
    deleteUrl: 'Hapus URL',
    urlManagement: 'Manajemen URL',
    shortUrlLabel: 'URL Pendek',
    targetUrlLabel: 'URL Target',
    titleLabel: 'Judul',
    descriptionLabel: 'Deskripsi',
    expirationLabel: 'Kedaluwarsa',
    activeLabel: 'Aktif',
    inactiveLabel: 'Tidak Aktif',
    hitCountLabel: 'Jumlah Hits',
    createdAtLabel: 'Dibuat',
    actionsLabel: 'Aksi',
    save: 'Simpan',
    deleteAction: 'Hapus',
    confirmAction: 'Konfirmasi',
    search: 'Cari',
    filter: 'Filter',
    all: 'Semua',
    noUrlsFound: 'Tidak ada URL ditemukan',
    totalUrls: 'Total URL',
    activeUrls: 'URL Aktif',
    totalHits: 'Total Hits',
    backToDashboard: 'Kembali ke Dashboard',
    changeLanguage: 'Ubah Bahasa',
    cancelAction: 'Batal',
  },
  en: {
    loading: 'Loading...',
    urlNotFound: 'URL Not Found',
    urlNotFoundMessage: 'The URL you are looking for does not exist or has been removed.',
    goToHomepage: 'Go to Homepage',
    passwordProtected: 'Password Protected URL',
    accessBlocked: 'Access Blocked',
    enterPassword: 'Enter Password',
    passwordPlaceholder: 'Enter password',
    unlock: 'Unlock',
    verifying: 'Verifying...',
    attempts: 'Attempts',
    caseSensitive: 'Password case-sensitive',
    wrongPassword: 'Wrong password',
    remainingAttempts: 'Remaining attempts',
    maxAttemptsReached: 'You have exceeded maximum attempts',
    tips: 'Tips',
    caseSensitiveTip: 'Password is case-sensitive (uppercase/lowercase matters). Make sure Caps Lock is off.',
    contactOwner: 'Contact the link owner to get the correct password.',
    publicAccess: 'Public access',
    protectedInfo: 'this information is protected',
    urlFound: 'URL Found!',
    redirecting: 'Redirecting in...',
    shortUrl: 'Short URL',
    linkInfo: 'Link Information',
    targetUrl: 'Target URL',
    preparing: 'Preparing redirect...',
    autoRedirectDisabled: 'Auto-redirect is disabled. Click the button to redirect.',
    redirectNow: 'Redirect Now',
    redirectingTo: 'You will be redirected to',
    redirectInSeconds: 'Redirecting to destination in {seconds} seconds...',
    passwordFailed: 'Attempt failed',
    welcomeTitle: 'Welcome to modernURL8',
    welcomeMessage: 'This is a URL redirection service. Please use a valid short URL to be redirected.',
    goToHome: 'Go to Homepage',
    notFoundTitle: 'Link Not Found',
    notFoundMessage: 'The short URL you entered does not exist or has been removed. Please check the URL and try again.',
    expiredTitle: 'Link Expired',
    expiredMessage: 'This short URL has expired and is no longer available.',
    backToDashboard: 'Back to Dashboard',
    changeLanguage: 'Change Language',

    // Kelola Pages
    dashboard: 'Dashboard',
    urls: 'URLs',
    users: 'Users',
    settings: 'Settings',
    logout: 'Logout',
    manageUrls: 'Manage URL',
    createUrl: 'Create URL',
    editUrl: 'Edit URL',
    deleteUrl: 'Delete URL',
    urlManagement: 'URL Management',
    shortUrlLabel: 'Short URL',
    targetUrlLabel: 'Target URL',
    titleLabel: 'Title',
    descriptionLabel: 'Description',
    expirationLabel: 'Expiration',
    activeLabel: 'Active',
    inactiveLabel: 'Inactive',
    hitCountLabel: 'Hit Count',
    createdAtLabel: 'Created',
    actionsLabel: 'Actions',
    save: 'Save',
    deleteAction: 'Delete',
    confirmAction: 'Confirm',
    search: 'Search',
    filter: 'Filter',
    all: 'All',
    noUrlsFound: 'No URLs found',
    totalUrls: 'Total URLs',
    activeUrls: 'Active URLs',
    totalHits: 'Total Hits',
    cancelAction: 'Cancel',
  },
  de: {
    loading: 'Laden...',
    urlNotFound: 'URL nicht gefunden',
    urlNotFoundMessage: 'Die gesuchte URL existiert nicht oder wurde entfernt.',
    goToHomepage: 'Zur Startseite',
    passwordProtected: 'Passwortgeschützte URL',
    accessBlocked: 'Zugriff gesperrt',
    enterPassword: 'Passwort eingeben',
    passwordPlaceholder: 'Passwort eingeben',
    unlock: 'Entsperren',
    verifying: 'Überprüfen...',
    attempts: 'Versuche',
    caseSensitive: 'Passwort ist case-sensitive',
    wrongPassword: 'Falsches Passwort',
    remainingAttempts: 'Verbleibende Versuche',
    maxAttemptsReached: 'Sie haben die maximale Anzahl an Versuchen überschritten',
    tips: 'Tipps',
    caseSensitiveTip: 'Das Passwort ist case-sensitive (Groß-/Kleinschreibung). Stellen Sie sicher, dass Caps Lock nicht aktiviert ist.',
    contactOwner: 'Kontaktieren Sie den Link-Eigentümer für das richtige Passwort.',
    publicAccess: 'Öffentlicher Zugang',
    protectedInfo: 'diese Informationen sind geschützt',
    urlFound: 'URL gefunden!',
    redirecting: 'Weiterleitung in...',
    shortUrl: 'Kurz-URL',
    linkInfo: 'Link-Information',
    targetUrl: 'Ziel-URL',
    preparing: 'Weiterleitung vorbereiten...',
    autoRedirectDisabled: 'Auto-Weiterleitung ist deaktiviert. Klicken Sie auf die Schaltfläche zur Weiterleitung.',
    redirectNow: 'Jetzt weiterleiten',
    redirectingTo: 'Sie werden weitergeleitet zu',
    redirectInSeconds: 'Weiterleitung zum Ziel in {seconds} Sekunden...',
    passwordFailed: 'Versuch fehlgeschlagen',
    welcomeTitle: 'Willkommen bei modernURL8',
    welcomeMessage: 'Dies ist ein URL-Weiterleitungsdienst. Bitte verwenden Sie eine gültige Kurz-URL zur Weiterleitung.',
    goToHome: 'Zur Startseite',
    notFoundTitle: 'Link nicht gefunden',
    notFoundMessage: 'Die eingegebene Kurz-URL existiert nicht oder wurde entfernt. Bitte überprüfen Sie die URL und versuchen Sie es erneut.',
    expiredTitle: 'Link abgelaufen',
    expiredMessage: 'Diese Kurz-URL ist abgelaufen und nicht mehr verfügbar.',
    backToDashboard: 'Zurück zum Dashboard',
    changeLanguage: 'Sprache ändern',

    // Kelola Pages
    dashboard: 'Dashboard',
    urls: 'URLs',
    users: 'Benutzer',
    settings: 'Einstellungen',
    logout: 'Abmelden',
    manageUrls: 'URL verwalten',
    createUrl: 'URL erstellen',
    editUrl: 'URL bearbeiten',
    deleteUrl: 'URL löschen',
    urlManagement: 'URL-Verwaltung',
    shortUrlLabel: 'Kurz-URL',
    targetUrlLabel: 'Ziel-URL',
    titleLabel: 'Titel',
    descriptionLabel: 'Beschreibung',
    expirationLabel: 'Ablauf',
    activeLabel: 'Aktiv',
    inactiveLabel: 'Inaktiv',
    hitCountLabel: 'Zugriffe',
    createdAtLabel: 'Erstellt',
    actionsLabel: 'Aktionen',
    save: 'Speichern',
    deleteAction: 'Löschen',
    confirmAction: 'Bestätigen',
    search: 'Suchen',
    filter: 'Filtern',
    all: 'Alle',
    noUrlsFound: 'Keine URLs gefunden',
    totalUrls: 'Gesamte URLs',
    activeUrls: 'Aktive URLs',
    totalHits: 'Gesamte Zugriffe',
    cancelAction: 'Abbrechen',
  },
  zh: {
    loading: '加载中...',
    urlNotFound: 'URL未找到',
    urlNotFoundMessage: '您要查找的URL不存在或已被删除。',
    goToHomepage: '返回首页',
    passwordProtected: '密码保护的URL',
    accessBlocked: '访问被阻止',
    enterPassword: '输入密码',
    passwordPlaceholder: '输入密码',
    unlock: '解锁',
    verifying: '验证中...',
    attempts: '尝试次数',
    caseSensitive: '密码区分大小写',
    wrongPassword: '密码错误',
    remainingAttempts: '剩余尝试次数',
    maxAttemptsReached: '您已超过最大尝试次数',
    tips: '提示',
    caseSensitiveTip: '密码区分大小写（请注意大写和小写）。请确保Caps Lock未开启。',
    contactOwner: '请联系链接所有者获取正确的密码。',
    publicAccess: '公开访问',
    protectedInfo: '此信息受保护',
    urlFound: 'URL已找到！',
    redirecting: '重定向中...',
    shortUrl: '短URL',
    linkInfo: '链接信息',
    targetUrl: '目标URL',
    preparing: '准备重定向...',
    autoRedirectDisabled: '自动重定向已禁用。点击按钮进行重定向。',
    redirectNow: '立即重定向',
    redirectingTo: '您将被重定向到',
    redirectInSeconds: '{seconds}秒后重定向到目标...',
    passwordFailed: '尝试失败',
    welcomeTitle: '欢迎使用 modernURL8',
    welcomeMessage: '这是一个URL重定向服务。请使用有效的短URL进行重定向。',
    goToHome: '返回首页',
    notFoundTitle: '链接未找到',
    notFoundMessage: '您输入的短URL不存在或已被删除。请检查URL并重试。',
    expiredTitle: '链接已过期',
    expiredMessage: '此短URL已过期，不再可用。',
    backToDashboard: '返回仪表板',
    changeLanguage: '更改语言',

    // Kelola Pages
    dashboard: '仪表板',
    urls: '链接',
    users: '用户',
    settings: '设置',
    logout: '退出',
    manageUrls: '管理链接',
    createUrl: '创建链接',
    editUrl: '编辑链接',
    deleteUrl: '删除链接',
    urlManagement: '链接管理',
    shortUrlLabel: '短链接',
    targetUrlLabel: '目标链接',
    titleLabel: '标题',
    descriptionLabel: '描述',
    expirationLabel: '过期时间',
    activeLabel: '活跃',
    inactiveLabel: '未激活',
    hitCountLabel: '访问次数',
    createdAtLabel: '创建时间',
    actionsLabel: '操作',
    save: '保存',
    deleteAction: '删除',
    confirmAction: '确认',
    search: '搜索',
    filter: '筛选',
    all: '全部',
    noUrlsFound: '未找到链接',
    totalUrls: '总链接数',
    activeUrls: '活跃链接',
    totalHits: '总访问次数',
    cancelAction: '取消',
  },
  ja: {
    loading: '読み込み中...',
    urlNotFound: 'URLが見つかりません',
    urlNotFoundMessage: 'お探しのURLは存在しないか、削除されました。',
    goToHomepage: 'ホームページに戻る',
    passwordProtected: 'パスワード保護付きURL',
    accessBlocked: 'アクセスがブロックされました',
    enterPassword: 'パスワードを入力',
    passwordPlaceholder: 'パスワードを入力',
    unlock: 'ロック解除',
    verifying: '確認中...',
    attempts: '試行回数',
    caseSensitive: 'パスワードは大文字と小文字を区別します',
    wrongPassword: 'パスワードが正しくありません',
    remainingAttempts: '残り試行回数',
    maxAttemptsReached: '最大試行回数を超えました',
    tips: 'ヒント',
    caseSensitiveTip: 'パスワードは大文字と小文字を区別します（Caps Lockがオフになっていることを確認してください）。',
    contactOwner: 'リンクの所有者に正しいパスワードを確認してください。',
    publicAccess: 'パブリックアクセス',
    protectedInfo: 'この情報は保護されています',
    urlFound: 'URLが見つかりました！',
    redirecting: 'リダイレクト中...',
    shortUrl: 'ショートURL',
    linkInfo: 'リンク情報',
    targetUrl: 'ターゲットURL',
    preparing: 'リダイレクトを準備中...',
    autoRedirectDisabled: '自動リダイレクトが無効になっています。ボタンをクリックしてリダイレクトしてください。',
    redirectNow: '今すぐリダイレクト',
    redirectingTo: 'リダイレクト先：',
    redirectInSeconds: '{seconds}秒後に宛先にリダイレクトします...',
    passwordFailed: '試行に失敗しました',
    welcomeTitle: 'modernURL8へようこそ',
    welcomeMessage: 'これはURLリダイレクトサービス です。有効なショートURLを使用してリダイレクトしてください。',
    goToHome: 'ホームページへ',
    notFoundTitle: 'リンクが見つかりません',
    notFoundMessage: '入力したショートURLは存在しないか、削除されました。URLを確認して再試行してください。',
    expiredTitle: 'リンクの有効期限が切れました',
    expiredMessage: 'このショートURLは有効期限が切れ、利用できなくなりました。',
    backToDashboard: 'ダッシュボードに戻る',
    changeLanguage: '言語を変更',

    // Kelola Pages
    dashboard: 'ダッシュボード',
    urls: 'URL',
    users: 'ユーザー',
    settings: '設定',
    logout: 'ログアウト',
    manageUrls: 'URL管理',
    createUrl: 'URL作成',
    editUrl: 'URL編集',
    deleteUrl: 'URL削除',
    urlManagement: 'URL管理',
    shortUrlLabel: 'ショートURL',
    targetUrlLabel: 'ターゲットURL',
    titleLabel: 'タイトル',
    descriptionLabel: '説明',
    expirationLabel: '有効期限',
    activeLabel: 'アクティブ',
    inactiveLabel: '非アクティブ',
    hitCountLabel: 'アクセス数',
    createdAtLabel: '作成日',
    actionsLabel: 'アクション',
    save: '保存',
    deleteAction: '削除',
    confirmAction: '確認',
    search: '検索',
    filter: 'フィルター',
    all: 'すべて',
    noUrlsFound: 'URLが見つかりません',
    totalUrls: 'URL総数',
    activeUrls: 'アクティブURL',
    totalHits: '総アクセス数',
    cancelAction: 'キャンセル',
  },
  es: {
    loading: 'Cargando...',
    urlNotFound: 'URL no encontrada',
    urlNotFoundMessage: 'La URL que buscas no existe o ha sido eliminada.',
    goToHomepage: 'Ir a inicio',
    passwordProtected: 'URL protegida con contraseña',
    accessBlocked: 'Acceso bloqueado',
    enterPassword: 'Ingrese contraseña',
    passwordPlaceholder: 'Ingrese contraseña',
    unlock: 'Desbloquear',
    verifying: 'Verificando...',
    attempts: 'Intentos',
    caseSensitive: 'Contraseña distingue mayúsculas/minúsculas',
    wrongPassword: 'Contraseña incorrecta',
    remainingAttempts: 'Intentos restantes',
    maxAttemptsReached: 'Ha excedido el número máximo de intentos',
    tips: 'Consejos',
    caseSensitiveTip: 'La contraseña distingue mayúsculas de minúsculas. Asegúrese de que Bloq Mayús no esté activado.',
    contactOwner: 'Contacte al propietario del enlace para obtener la contraseña correcta.',
    publicAccess: 'Acceso público',
    protectedInfo: 'esta información está protegida',
    urlFound: '¡URL encontrada!',
    redirecting: 'Redirigiendo en...',
    shortUrl: 'URL corta',
    linkInfo: 'Información del enlace',
    targetUrl: 'URL de destino',
    preparing: 'Preparando redirección...',
    autoRedirectDisabled: 'La redirección automática está deshabilitada. Haga clic en el botón para redirigir.',
    redirectNow: 'Redirigir ahora',
    redirectingTo: 'Será redirigido a',
    redirectInSeconds: 'Redirigiendo al destino en {seconds} segundos...',
    passwordFailed: 'Intento fallido',
    welcomeTitle: 'Bienvenido a modernURL8',
    welcomeMessage: 'Este es un servicio de redirección de URL. Por favor use una URL corta válida para ser redirigido.',
    goToHome: 'Ir al inicio',
    notFoundTitle: 'Enlace no encontrado',
    notFoundMessage: 'La URL corta que ingresó no existe o ha sido eliminada. Por favor verifique la URL e intente de nuevo.',
    expiredTitle: 'Enlace expirado',
    expiredMessage: 'Esta URL corta ha expirado y ya no está disponible.',
    backToDashboard: 'Volver al panel',
    changeLanguage: 'Cambiar idioma',

    // Kelola Pages
    dashboard: 'Panel',
    urls: 'URLs',
    users: 'Usuarios',
    settings: 'Configuración',
    logout: 'Cerrar sesión',
    manageUrls: 'Gestionar URL',
    createUrl: 'Crear URL',
    editUrl: 'Editar URL',
    deleteUrl: 'Eliminar URL',
    urlManagement: 'Gestión de URL',
    shortUrlLabel: 'URL corta',
    targetUrlLabel: 'URL de destino',
    titleLabel: 'Título',
    descriptionLabel: 'Descripción',
    expirationLabel: 'Vencimiento',
    activeLabel: 'Activo',
    inactiveLabel: 'Inactivo',
    hitCountLabel: 'Visitas',
    createdAtLabel: 'Creado',
    actionsLabel: 'Acciones',
    save: 'Guardar',
    deleteAction: 'Eliminar',
    confirmAction: 'Confirmar',
    search: 'Buscar',
    filter: 'Filtrar',
    all: 'Todos',
    noUrlsFound: 'No se encontraron URLs',
    totalUrls: 'Total de URLs',
    activeUrls: 'URLs activas',
    totalHits: 'Visitas totales',
    cancelAction: 'Cancelar',
  },
  pt: {
    loading: 'Carregando...',
    urlNotFound: 'URL não encontrada',
    urlNotFoundMessage: 'O URL que você procura não existe ou foi removido.',
    goToHomepage: 'Ir para início',
    passwordProtected: 'URL protegida por senha',
    accessBlocked: 'Acesso bloqueado',
    enterPassword: 'Digite a senha',
    passwordPlaceholder: 'Digite a senha',
    unlock: 'Desbloquear',
    verifying: 'Verificando...',
    attempts: 'Tentativas',
    caseSensitive: 'Senha é case-sensitive',
    wrongPassword: 'Senha incorreta',
    remainingAttempts: 'Tentativas restantes',
    maxAttemptsReached: 'Você excedeu o número máximo de tentativas',
    tips: 'Dicas',
    caseSensitiveTip: 'A senha é case-sensitive (maiúsculas/minúsculas). Certifique-se de que o Caps Lock não está ativado.',
    contactOwner: 'Entre em contato com o proprietário do link para obter a senha correta.',
    publicAccess: 'Acesso público',
    protectedInfo: 'esta informação está protegida',
    urlFound: 'URL encontrada!',
    redirecting: 'Redirecionando em...',
    shortUrl: 'URL curta',
    linkInfo: 'Informações do link',
    targetUrl: 'URL de destino',
    preparing: 'Preparando redirecionamento...',
    autoRedirectDisabled: 'O redirecionamento automático está desativado. Clique no botão para redirecionar.',
    redirectNow: 'Redirecionar agora',
    redirectingTo: 'Você será redirecionado para',
    redirectInSeconds: 'Redirecionando para o destino em {seconds} segundos...',
    passwordFailed: 'Tentativa falhou',
    welcomeTitle: 'Bem-vindo ao modernURL8',
    welcomeMessage: 'Este é um serviço de redirecionamento de URL. Por favor, use uma URL curta válida para ser redirecionado.',
    goToHome: 'Ir para início',
    notFoundTitle: 'Link não encontrado',
    notFoundMessage: 'A URL curta que você inseriu não existe ou foi removida. Por favor, verifique a URL e tente novamente.',
    expiredTitle: 'Link expirado',
    expiredMessage: 'Esta URL curta expirou e não está mais disponível.',
    backToDashboard: 'Voltar ao painel',
    changeLanguage: 'Mudar idioma',

    // Kelola Pages
    dashboard: 'Painel',
    urls: 'URLs',
    users: 'Usuários',
    settings: 'Configurações',
    logout: 'Sair',
    manageUrls: 'Gerenciar URL',
    createUrl: 'Criar URL',
    editUrl: 'Editar URL',
    deleteUrl: 'Excluir URL',
    urlManagement: 'Gerenciamento de URL',
    shortUrlLabel: 'URL curta',
    targetUrlLabel: 'URL de destino',
    titleLabel: 'Título',
    descriptionLabel: 'Descrição',
    expirationLabel: 'Expiração',
    activeLabel: 'Ativo',
    inactiveLabel: 'Inativo',
    hitCountLabel: 'Acessos',
    createdAtLabel: 'Criado',
    actionsLabel: 'Ações',
    save: 'Salvar',
    deleteAction: 'Excluir',
    confirmAction: 'Confirmar',
    search: 'Pesquisar',
    filter: 'Filtrar',
    all: 'Todos',
    noUrlsFound: 'Nenhuma URL encontrada',
    totalUrls: 'Total de URLs',
    activeUrls: 'URLs ativas',
    totalHits: 'Total de acessos',
    cancelAction: 'Cancelar',
  },
  fr: {
    loading: 'Chargement...',
    urlNotFound: 'URL non trouvée',
    urlNotFoundMessage: "L'URL que vous recherchez n'existe pas ou a été supprimée.",
    goToHomepage: 'Aller à la page d\'accueil',
    passwordProtected: 'URL protégée par mot de passe',
    accessBlocked: 'Accès bloqué',
    enterPassword: 'Entrez le mot de passe',
    passwordPlaceholder: 'Entrez le mot de passe',
    unlock: 'Déverrouiller',
    verifying: 'Vérification...',
    attempts: 'Tentatives',
    caseSensitive: 'Mot de passe sensible à la casse',
    wrongPassword: 'Mot de passe incorrect',
    remainingAttempts: 'Tentatives restantes',
    maxAttemptsReached: 'Vous avez dépassé le nombre maximum de tentatives',
    tips: 'Conseils',
    caseSensitiveTip: 'Le mot de passe est sensible à la casse (majuscules/minuscules). Assurez-vous que Verr. Maj. est désactivé.',
    contactOwner: 'Contactez le propriétaire du lien pour obtenir le mot de passe correct.',
    publicAccess: 'Accès public',
    protectedInfo: 'cette information est protégée',
    urlFound: 'URL trouvée !',
    redirecting: 'Redirection dans...',
    shortUrl: 'URL courte',
    linkInfo: 'Informations du lien',
    targetUrl: 'URL de destination',
    preparing: 'Préparation de la redirection...',
    autoRedirectDisabled: 'La redirection automatique est désactivée. Cliquez sur le bouton pour rediriger.',
    redirectNow: 'Rediriger maintenant',
    redirectingTo: 'Vous serez redirigé vers',
    redirectInSeconds: 'Redirection vers la destination dans {seconds} secondes...',
    passwordFailed: 'Tentative échouée',
    welcomeTitle: 'Bienvenue sur modernURL8',
    welcomeMessage: "Ceci est un service de redirection d'URL. Veuillez utiliser une URL courte valide pour être redirigé.",
    goToHome: 'Aller à l\'accueil',
    notFoundTitle: 'Lien non trouvé',
    notFoundMessage: "L'URL courte que vous avez saisie n'existe pas ou a été supprimée. Veuillez vérifier l'URL et réessayer.",
    expiredTitle: 'Lien expiré',
    expiredMessage: 'Cette URL courte a expiré et n\'est plus disponible.',
    backToDashboard: 'Retour au tableau de bord',
    changeLanguage: 'Changer de langue',

    // Kelola Pages
    dashboard: 'Tableau de bord',
    urls: 'URLs',
    users: 'Utilisateurs',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    manageUrls: 'Gérer les URLs',
    createUrl: 'Créer une URL',
    editUrl: 'Modifier l\'URL',
    deleteUrl: 'Supprimer l\'URL',
    urlManagement: 'Gestion des URLs',
    shortUrlLabel: 'URL courte',
    targetUrlLabel: 'URL cible',
    titleLabel: 'Titre',
    descriptionLabel: 'Description',
    expirationLabel: 'Expiration',
    activeLabel: 'Actif',
    inactiveLabel: 'Inactif',
    hitCountLabel: 'Visites',
    createdAtLabel: 'Créé',
    actionsLabel: 'Actions',
    save: 'Enregistrer',
    deleteAction: 'Supprimer',
    confirmAction: 'Confirmer',
    search: 'Rechercher',
    filter: 'Filtrer',
    all: 'Tous',
    noUrlsFound: 'Aucune URL trouvée',
    totalUrls: 'Total des URLs',
    activeUrls: 'URLs actives',
    totalHits: 'Total des visites',
    cancelAction: 'Annuler',
  },
};

const AVAILABLE_LANGUAGES = [
  { code: 'id' as Language, label: 'Indonesia', flag: '🇮🇩' },
  { code: 'en' as Language, label: 'English', flag: '🇬🇧' },
  { code: 'de' as Language, label: 'Deutsch', flag: '🇩🇪' },
  { code: 'zh' as Language, label: '中文', flag: '🇨🇳' },
  { code: 'ja' as Language, label: '日本語', flag: '🇯🇵' },
  { code: 'es' as Language, label: 'Español', flag: '🇪🇸' },
  { code: 'pt' as Language, label: 'Português', flag: '🇧🇷' },
  { code: 'fr' as Language, label: 'Français', flag: '🇫🇷' },
];

const LanguageContext = createContext<LanguageContextType>({
  language: 'id',
  setLanguage: () => {},
  t: (key: string) => key,
  availableLanguages: AVAILABLE_LANGUAGES,
  ownerLanguage: null,
  setOwnerLanguage: () => {},
  effectiveLanguage: 'id',
  isPublicContext: false,
  setIsPublicContext: () => {},
});

export function useLanguage() {
  return useContext(LanguageContext);
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const { settings } = useSettings();
  const { user, isAuthenticated } = useAuth();
  
  // User's authenticated language preference (for Kelola pages)
  const [language, setLanguageState] = useState<Language>('id');
  // Owner's language (for public pages - fetched from URL owner)
  const [ownerLanguage, setOwnerLanguage] = useState<Language | null>(null);
  // Flag to determine if we're in public context
  const [isPublicContext, setIsPublicContext] = useState(false);

  // Determine effective language based on context
  const effectiveLanguage = isPublicContext && ownerLanguage 
    ? ownerLanguage 
    : language;

  // Initialize language from multiple sources (priority order)
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    
    if (savedLanguage && AVAILABLE_LANGUAGES.some(l => l.code === savedLanguage)) {
      setLanguageState(savedLanguage);
    } else if (user?.language && AVAILABLE_LANGUAGES.some(l => l.code === (user.language as Language))) {
      // Use user's language preference from database
      setLanguageState(user.language as Language);
    } else {
      // Fall back to app default
      const defaultLang = settings.defaultLanguage as Language;
      if (AVAILABLE_LANGUAGES.some(l => l.code === defaultLang)) {
        setLanguageState(defaultLang);
      }
    }
  }, [settings.defaultLanguage, user]);

  // Save user's language preference to backend when authenticated
  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    
    // If user is authenticated, save to backend
    if (isAuthenticated && user) {
      try {
        await fetch(`/api8url/users/${user.id}`, {
          method: 'PUT',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${localStorage.getItem('token')}`,
          },
          body: JSON.stringify({ language: lang }),
        });
      } catch (err) {
        console.error('[LanguageContext] Failed to save language preference:', err);
      }
    }
  };

  // Translation function using effective language
  const t = (key: string): string => {
    const langToUse = effectiveLanguage;
    return translations[langToUse]?.[key] || translations['id']?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage, 
      t, 
      availableLanguages: AVAILABLE_LANGUAGES,
      ownerLanguage,
      setOwnerLanguage,
      effectiveLanguage,
      isPublicContext,
      setIsPublicContext,
    }}>
      {children}
    </LanguageContext.Provider>
  );
}
