import { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { useSettings } from './SettingsContext';

type Language = 'id' | 'en' | 'de' | 'zh' | 'ja' | 'es' | 'pt' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  availableLanguages: { code: Language; label: string; flag: string }[];
}

const translations: Record<Language, Record<string, string>> = {
  id: {
    // URL Found Page
    loading: 'Memuat...',
    urlNotFound: 'URL Tidak Ditemukan',
    urlNotFoundMessage: 'Tautan yang Anda cari tidak ditemukan atau telah dihapus.',
    goToHomepage: 'Kembali ke Beranda',
    passwordProtected: 'URL Dilindungi Password',
    accessBlocked: 'Akses Diblokir',
    enterPassword: 'Masukkan Password',
    passwordPlaceholder: 'Masukkan password',
    unlock: 'Buka Kunci',
    verifying: 'Memverifikasi...',
    attempts: 'Percobaan',
    caseSensitive: 'Password case-sensitive',
    wrongPassword: 'Password salah',
    remainingAttempts: 'Sisa percobaan',
    maxAttemptsReached: 'Anda telah melebihi percobaan maksimal',
    tips: 'Tips',
    caseSensitiveTip: 'Password bersifat case-sensitive (huruf besar/kecil berbeda). Pastikan Caps Lock tidak aktif.',
    contactOwner: 'Hubungi pemilik tautan untuk mendapatkan password yang benar.',
    publicAccess: 'Akses publik',
    protectedInfo: 'informasi ini dilindungi',
    urlFound: 'URL Ditemukan!',
    redirecting: 'Redirect dalam...',
    shortUrl: 'Short URL',
    linkInfo: 'Informasi Link',
    targetUrl: 'Target URL',
    preparing: 'Mempersiapkan redirect...',
    autoRedirectDisabled: 'Auto-redirect dinonaktifkan. Klik tombol untuk redirect.',
    cancel: 'Batal',
    redirectNow: 'Redirect Sekarang',
    redirectingTo: 'Anda akan diarahkan ke',
    redirectInSeconds: 'Mengalihkan ke halaman tujuan dalam {seconds} detik...',
    passwordFailed: 'Percobaan gagal',
    
    // Public HTML Pages
    welcomeTitle: 'Selamat Datang di modernURL8',
    welcomeMessage: 'Ini adalah layanan pengalihan URL. Silakan gunakan URL pendek yang valid untuk dialihkan.',
    goToHome: 'Ke Beranda',
    notFoundTitle: 'Tautan Tidak Ditemukan',
    notFoundMessage: 'URL pendek yang Anda masukkan tidak ada atau telah dihapus. Silakan periksa URL dan coba lagi.',
    expiredTitle: 'Tautan Kadaluarsa',
    expiredMessage: 'URL pendek ini telah kedaluwarsa dan tidak lagi tersedia.',
    
    // General
    backToDashboard: 'Kembali ke Dashboard',
  },
  en: {
    loading: 'Loading...',
    urlNotFound: 'URL Not Found',
    urlNotFoundMessage: 'The URL you are looking for does not exist or has been removed.',
    goToHomepage: 'Go to Homepage',
    passwordProtected: 'Password Protected URL',
    accessBlocked: 'Access Blocked',
    enterPassword: 'Enter Password',
    passwordPlaceholder: 'Enter password',
    unlock: 'Unlock',
    verifying: 'Verifying...',
    attempts: 'Attempts',
    caseSensitive: 'Password case-sensitive',
    wrongPassword: 'Wrong password',
    remainingAttempts: 'Remaining attempts',
    maxAttemptsReached: 'You have exceeded maximum attempts',
    tips: 'Tips',
    caseSensitiveTip: 'Password is case-sensitive (uppercase/lowercase matters). Make sure Caps Lock is off.',
    contactOwner: 'Contact the link owner to get the correct password.',
    publicAccess: 'Public access',
    protectedInfo: 'this information is protected',
    urlFound: 'URL Found!',
    redirecting: 'Redirecting in...',
    shortUrl: 'Short URL',
    linkInfo: 'Link Information',
    targetUrl: 'Target URL',
    preparing: 'Preparing redirect...',
    autoRedirectDisabled: 'Auto-redirect is disabled. Click the button to redirect.',
    cancel: 'Cancel',
    redirectNow: 'Redirect Now',
    redirectingTo: 'You will be redirected to',
    redirectInSeconds: 'Redirecting to destination in {seconds} seconds...',
    passwordFailed: 'Attempt failed',
    welcomeTitle: 'Welcome to modernURL8',
    welcomeMessage: 'This is a URL redirection service. Please use a valid short URL to be redirected.',
    goToHome: 'Go to Homepage',
    notFoundTitle: 'Link Not Found',
    notFoundMessage: 'The short URL you entered does not exist or has been removed. Please check the URL and try again.',
    expiredTitle: 'Link Expired',
    expiredMessage: 'This short URL has expired and is no longer available.',
    backToDashboard: 'Back to Dashboard',
  },
  de: {
    loading: 'Laden...',
    urlNotFound: 'URL nicht gefunden',
    urlNotFoundMessage: 'Die gesuchte URL existiert nicht oder wurde entfernt.',
    goToHomepage: 'Zur Startseite',
    passwordProtected: 'Passwortgeschützte URL',
    accessBlocked: 'Zugriff gesperrt',
    enterPassword: 'Passwort eingeben',
    passwordPlaceholder: 'Passwort eingeben',
    unlock: 'Entsperren',
    verifying: 'Überprüfen...',
    attempts: 'Versuche',
    caseSensitive: 'Passwort ist case-sensitive',
    wrongPassword: 'Falsches Passwort',
    remainingAttempts: 'Verbleibende Versuche',
    maxAttemptsReached: 'Sie haben die maximale Anzahl an Versuchen überschritten',
    tips: 'Tipps',
    caseSensitiveTip: 'Das Passwort ist case-sensitive (Groß-/Kleinschreibung). Stellen Sie sicher, dass Caps Lock nicht aktiviert ist.',
    contactOwner: 'Kontaktieren Sie den Link-Eigentümer für das richtige Passwort.',
    publicAccess: 'Öffentlicher Zugang',
    protectedInfo: 'diese Informationen sind geschützt',
    urlFound: 'URL gefunden!',
    redirecting: 'Weiterleitung in...',
    shortUrl: 'Kurz-URL',
    linkInfo: 'Link-Information',
    targetUrl: 'Ziel-URL',
    preparing: 'Weiterleitung vorbereiten...',
    autoRedirectDisabled: 'Auto-Weiterleitung ist deaktiviert. Klicken Sie auf die Schaltfläche zur Weiterleitung.',
    cancel: 'Abbrechen',
    redirectNow: 'Jetzt weiterleiten',
    redirectingTo: 'Sie werden weitergeleitet zu',
    redirectInSeconds: 'Weiterleitung zum Ziel in {seconds} Sekunden...',
    passwordFailed: 'Versuch fehlgeschlagen',
    welcomeTitle: 'Willkommen bei modernURL8',
    welcomeMessage: 'Dies ist ein URL-Weiterleitungsdienst. Bitte verwenden Sie eine gültige Kurz-URL zur Weiterleitung.',
    goToHome: 'Zur Startseite',
    notFoundTitle: 'Link nicht gefunden',
    notFoundMessage: 'Die eingegebene Kurz-URL existiert nicht oder wurde entfernt. Bitte überprüfen Sie die URL und versuchen Sie es erneut.',
    expiredTitle: 'Link abgelaufen',
    expiredMessage: 'Diese Kurz-URL ist abgelaufen und nicht mehr verfügbar.',
    backToDashboard: 'Zurück zum Dashboard',
  },
  zh: {
    loading: '加载中...',
    urlNotFound: 'URL未找到',
    urlNotFoundMessage: '您要查找的URL不存在或已被删除。',
    goToHomepage: '返回首页',
    passwordProtected: '密码保护的URL',
    accessBlocked: '访问被阻止',
    enterPassword: '输入密码',
    passwordPlaceholder: '输入密码',
    unlock: '解锁',
    verifying: '验证中...',
    attempts: '尝试次数',
    caseSensitive: '密码区分大小写',
    wrongPassword: '密码错误',
    remainingAttempts: '剩余尝试次数',
    maxAttemptsReached: '您已超过最大尝试次数',
    tips: '提示',
    caseSensitiveTip: '密码区分大小写（请注意大写和小写）。请确保Caps Lock未开启。',
    contactOwner: '请联系链接所有者获取正确的密码。',
    publicAccess: '公开访问',
    protectedInfo: '此信息受保护',
    urlFound: 'URL已找到！',
    redirecting: '重定向中...',
    shortUrl: '短URL',
    linkInfo: '链接信息',
    targetUrl: '目标URL',
    preparing: '准备重定向...',
    autoRedirectDisabled: '自动重定向已禁用。点击按钮进行重定向。',
    cancel: '取消',
    redirectNow: '立即重定向',
    redirectingTo: '您将被重定向到',
    redirectInSeconds: '{seconds}秒后重定向到目标...',
    passwordFailed: '尝试失败',
    welcomeTitle: '欢迎使用 modernURL8',
    welcomeMessage: '这是一个URL重定向服务。请使用有效的短URL进行重定向。',
    goToHome: '返回首页',
    notFoundTitle: '链接未找到',
    notFoundMessage: '您输入的短URL不存在或已被删除。请检查URL并重试。',
    expiredTitle: '链接已过期',
    expiredMessage: '此短URL已过期，不再可用。',
    backToDashboard: '返回仪表板',
  },
  ja: {
    loading: '読み込み中...',
    urlNotFound: 'URLが見つかりません',
    urlNotFoundMessage: 'お探しのURLは存在しないか、削除されました。',
    goToHomepage: 'ホームページに戻る',
    passwordProtected: 'パスワード保護付きURL',
    accessBlocked: 'アクセスがブロックされました',
    enterPassword: 'パスワードを入力',
    passwordPlaceholder: 'パスワードを入力',
    unlock: 'ロック解除',
    verifying: '確認中...',
    attempts: '試行回数',
    caseSensitive: 'パスワードは大文字と小文字を区別します',
    wrongPassword: 'パスワードが正しくありません',
    remainingAttempts: '残り試行回数',
    maxAttemptsReached: '最大試行回数を超えました',
    tips: 'ヒント',
    caseSensitiveTip: 'パスワードは大文字と小文字を区別します（Caps Lockがオフになっていることを確認してください）。',
    contactOwner: 'リンクの所有者に正しいパスワードを確認してください。',
    publicAccess: 'パブリックアクセス',
    protectedInfo: 'この情報は保護されています',
    urlFound: 'URLが見つかりました！',
    redirecting: 'リダイレクト中...',
    shortUrl: 'ショートURL',
    linkInfo: 'リンク情報',
    targetUrl: 'ターゲットURL',
    preparing: 'リダイレクトを準備中...',
    autoRedirectDisabled: '自動リダイレクトが無効になっています。ボタンをクリックしてリダイレクトしてください。',
    cancel: 'キャンセル',
    redirectNow: '今すぐリダイレクト',
    redirectingTo: 'リダイレクト先：',
    redirectInSeconds: '{seconds}秒後に宛先にリダイレクトします...',
    passwordFailed: '試行に失敗しました',
    welcomeTitle: 'modernURL8へようこそ',
    welcomeMessage: 'これはURLリダイレクトサービス 입니다。有効なショートURLを使用してリダイレクトしてください。',
    goToHome: 'ホームページへ',
    notFoundTitle: 'リンクが見つかりません',
    notFoundMessage: '入力したショートURLは存在しないか、削除されました。URLを確認して再試行してください。',
    expiredTitle: 'リンクの有効期限が切れました',
    expiredMessage: 'このショートURLは有効期限が切れ、利用できなくなりました。',
    backToDashboard: 'ダッシュボードに戻る',
  },
  es: {
    loading: 'Cargando...',
    urlNotFound: 'URL no encontrada',
    urlNotFoundMessage: 'La URL que buscas no existe o ha sido eliminada.',
    goToHomepage: 'Ir a inicio',
    passwordProtected: 'URL protegida con contraseña',
    accessBlocked: 'Acceso bloqueado',
    enterPassword: 'Ingrese contraseña',
    passwordPlaceholder: 'Ingrese contraseña',
    unlock: 'Desbloquear',
    verifying: 'Verificando...',
    attempts: 'Intentos',
    caseSensitive: 'Contraseña distingue mayúsculas/minúsculas',
    wrongPassword: 'Contraseña incorrecta',
    remainingAttempts: 'Intentos restantes',
    maxAttemptsReached: 'Ha excedido el número máximo de intentos',
    tips: 'Consejos',
    caseSensitiveTip: 'La contraseña distingue mayúsculas de minúsculas. Asegúrese de que Bloq Mayús no esté activado.',
    contactOwner: 'Contacte al propietario del enlace para obtener la contraseña correcta.',
    publicAccess: 'Acceso público',
    protectedInfo: 'esta información está protegida',
    urlFound: '¡URL encontrada!',
    redirecting: 'Redirigiendo en...',
    shortUrl: 'URL corta',
    linkInfo: 'Información del enlace',
    targetUrl: 'URL de destino',
    preparing: 'Preparando redirección...',
    autoRedirectDisabled: 'La redirección automática está deshabilitada. Haga clic en el botón para redirigir.',
    cancel: 'Cancelar',
    redirectNow: 'Redirigir ahora',
    redirectingTo: 'Será redirigido a',
    redirectInSeconds: 'Redirigiendo al destino en {seconds} segundos...',
    passwordFailed: 'Intento fallido',
    welcomeTitle: 'Bienvenido a modernURL8',
    welcomeMessage: 'Este es un servicio de redirección de URL. Por favor use una URL corta válida para ser redirigido.',
    goToHome: 'Ir al inicio',
    notFoundTitle: 'Enlace no encontrado',
    notFoundMessage: 'La URL corta que ingresó no existe o ha sido eliminada. Por favor verifique la URL e intente de nuevo.',
    expiredTitle: 'Enlace expirado',
    expiredMessage: 'Esta URL corta ha expirado y ya no está disponible.',
    backToDashboard: 'Volver al panel',
  },
  pt: {
    loading: 'Carregando...',
    urlNotFound: 'URL não encontrada',
    urlNotFoundMessage: 'O URL que você procura não existe ou foi removido.',
    goToHomepage: 'Ir para início',
    passwordProtected: 'URL protegida por senha',
    accessBlocked: 'Acesso bloqueado',
    enterPassword: 'Digite a senha',
    passwordPlaceholder: 'Digite a senha',
    unlock: 'Desbloquear',
    verifying: 'Verificando...',
    attempts: 'Tentativas',
    caseSensitive: 'Senha é case-sensitive',
    wrongPassword: 'Senha incorreta',
    remainingAttempts: 'Tentativas restantes',
    maxAttemptsReached: 'Você excedeu o número máximo de tentativas',
    tips: 'Dicas',
    caseSensitiveTip: 'A senha é case-sensitive (maiúsculas/minúsculas). Certifique-se de que o Caps Lock não está ativado.',
    contactOwner: 'Entre em contato com o proprietário do link para obter a senha correta.',
    publicAccess: 'Acesso público',
    protectedInfo: 'esta informação está protegida',
    urlFound: 'URL encontrada!',
    redirecting: 'Redirecionando em...',
    shortUrl: 'URL curta',
    linkInfo: 'Informações do link',
    targetUrl: 'URL de destino',
    preparing: 'Preparando redirecionamento...',
    autoRedirectDisabled: 'O redirecionamento automático está desativado. Clique no botão para redirecionar.',
    cancel: 'Cancelar',
    redirectNow: 'Redirecionar agora',
    redirectingTo: 'Você será redirecionado para',
    redirectInSeconds: 'Redirecionando para o destino em {seconds} segundos...',
    passwordFailed: 'Tentativa falhou',
    welcomeTitle: 'Bem-vindo ao modernURL8',
    welcomeMessage: 'Este é um serviço de redirecionamento de URL. Por favor, use uma URL curta válida para ser redirecionado.',
    goToHome: 'Ir para início',
    notFoundTitle: 'Link não encontrado',
    notFoundMessage: 'A URL curta que você inseriu não existe ou foi removida. Por favor, verifique a URL e tente novamente.',
    expiredTitle: 'Link expirado',
    expiredMessage: 'Esta URL curta expirou e não está mais disponível.',
    backToDashboard: 'Voltar ao painel',
  },
  fr: {
    loading: 'Chargement...',
    urlNotFound: 'URL non trouvée',
    urlNotFoundMessage: "L'URL que vous recherchez n'existe pas ou a été supprimée.",
    goToHomepage: 'Aller à la page d\'accueil',
    passwordProtected: 'URL protégée par mot de passe',
    accessBlocked: 'Accès bloqué',
    enterPassword: 'Entrez le mot de passe',
    passwordPlaceholder: 'Entrez le mot de passe',
    unlock: 'Déverrouiller',
    verifying: 'Vérification...',
    attempts: 'Tentatives',
    caseSensitive: 'Mot de passe sensible à la casse',
    wrongPassword: 'Mot de passe incorrect',
    remainingAttempts: 'Tentatives restantes',
    maxAttemptsReached: 'Vous avez dépassé le nombre maximum de tentatives',
    tips: 'Conseils',
    caseSensitiveTip: 'Le mot de passe est sensible à la casse (majuscules/minuscules). Assurez-vous que Verr. Maj. est désactivé.',
    contactOwner: 'Contactez le propriétaire du lien pour obtenir le mot de passe correct.',
    publicAccess: 'Accès public',
    protectedInfo: 'cette information est protégée',
    urlFound: 'URL trouvée !',
    redirecting: 'Redirection dans...',
    shortUrl: 'URL courte',
    linkInfo: 'Informations du lien',
    targetUrl: 'URL de destination',
    preparing: 'Préparation de la redirection...',
    autoRedirectDisabled: 'La redirection automatique est désactivée. Cliquez sur le bouton pour rediriger.',
    cancel: 'Annuler',
    redirectNow: 'Rediriger maintenant',
    redirectingTo: 'Vous serez redirigé vers',
    redirectInSeconds: 'Redirection vers la destination dans {seconds} secondes...',
    passwordFailed: 'Tentative échouée',
    welcomeTitle: 'Bienvenue sur modernURL8',
    welcomeMessage: "Ceci est un service de redirection d'URL. Veuillez utiliser une URL courte valide pour être redirigé.",
    goToHome: 'Aller à l\'accueil',
    notFoundTitle: 'Lien non trouvé',
    notFoundMessage: "L'URL courte que vous avez saisie n'existe pas ou a été supprimée. Veuillez vérifier l'URL et réessayer.",
    expiredTitle: 'Lien expiré',
    expiredMessage: 'Cette URL courte a expiré et n\'est plus disponible.',
    backToDashboard: 'Retour au tableau de bord',
  },
};

const AVAILABLE_LANGUAGES = [
  { code: 'id' as Language, label: 'Indonesia', flag: '🇮🇩' },
  { code: 'en' as Language, label: 'English', flag: '🇬🇧' },
  { code: 'de' as Language, label: 'Deutsch', flag: '🇩🇪' },
  { code: 'zh' as Language, label: '中文', flag: '🇨🇳' },
  { code: 'ja' as Language, label: '日本語', flag: '🇯🇵' },
  { code: 'es' as Language, label: 'Español', flag: '🇪🇸' },
  { code: 'pt' as Language, label: 'Português', flag: '🇧🇷' },
  { code: 'fr' as Language, label: 'Français', flag: '🇫🇷' },
];

const LanguageContext = createContext<LanguageContextType>({
  language: 'id',
  setLanguage: () => {},
  t: (key: string) => key,
  availableLanguages: AVAILABLE_LANGUAGES,
});

export function useLanguage() {
  return useContext(LanguageContext);
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const { settings } = useSettings();
  const [language, setLanguageState] = useState<Language>('id');

  // Initialize language from settings on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && AVAILABLE_LANGUAGES.some(l => l.code === savedLanguage)) {
      setLanguageState(savedLanguage);
    } else {
      // Use default from settings
      const defaultLang = settings.defaultLanguage as Language;
      if (AVAILABLE_LANGUAGES.some(l => l.code === defaultLang)) {
        setLanguageState(defaultLang);
      }
    }
  }, [settings.defaultLanguage]);

  // Save language preference
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  // Translation function
  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || translations['id']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, availableLanguages: AVAILABLE_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}
